<div class="hero-unit">
    <h1><?= sprintf($this->translate('__title_welcome_zsm'), '<span class="zf-green">', '</span>'); ?></h1>
    <p><?= sprintf($this->translate('__message_welcome_zsm'), '<a href="https://github.com/zendframework/ZendSkeletonModule" target="_blank">', '</a>', '<br />'); ?></p>
    <p><a class="btn btn-success btn-large" href="https://github.com/zendframework/ZendSkeletonModule" target="_blank"><?= $this->translate('__label_fork_zsm_on_github'); ?> &raquo;</a></p>
</div>